#!/usr/bin/python3
#
# Copyright 2012-2014 "Korora Project" <dev@kororaproject.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the temms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

import dnf
import hawkey
import os
import subprocess
import webbrowser

from lens.app import App
from lens.system import System

app = App(name="Welcome", width=792, height=496)

autostart_path = os.path.expanduser('~/.config/autostart/welcome.desktop')
autostart_state = False
system = System().to_dict()

app.namespaces = ['/usr/share/korora-welcome', 'data']

@app.bind('close-request')
def close_request_cb():
  app.close()

@app.connect('command')
def do_command_cb(cmd):
  if cmd == 'cinnamon-help':
    subprocess.Popen(['yelp'])

  elif cmd == 'gnome-help':
    subprocess.Popen(['yelp'])

  elif cmd == 'kde-help':
    subprocess.Popen(['khelpcenter'])

  elif cmd == 'xfce-help':
    subprocess.Popen(['xfce4-about'])

  elif cmd == 'install':
    subprocess.Popen(['/usr/bin/liveinst'])

@app.connect('get-system-config')
def get_config_cb(*args):
  app.emit('system-config', system)

@app.connect('open-url')
def open_url_cb(uri):
  webbrowser.open_new_tab(uri)

@app.connect('set-autostart')
def _app_close_cb(state):
  global autostart_state
  autostart_state = state

@app.connect('app.close')
def close_app_cb():
  if autostart_state and not os.path.exists(autostart_path):
    autostart_dir = os.path.dirname(autostart_path)

    # ensure destination dir exists
    if not os.path.exists(autostart_dir):
      os.makedirs(autostart_dir)

    os.symlink('/usr/share/applications/welcome.desktop', autostart_path)


try:
  # remove the autostart symlink
  os.unlink(autostart_path)
except:
  pass

app.start()
